language: c

env:
  - PPA=avsm/ocaml312+opam12 SWITCH=system
  - PPA=avsm/ocaml40+opam12 SWITCH=system
  - PPA=avsm/ocaml41+opam12 SWITCH=system
  - PPA=avsm/ocaml42+opam12 SWITCH=system
  - PPA=avsm/ocaml42+opam12 SWITCH=4.03.0
  - PPA=avsm/ocaml42+opam12 SWITCH=4.04.0 DOCS=yes COVERAGE=yes

before_script:
  - sudo add-apt-repository -y ppa:$PPA
  - sudo apt-get update
  - sudo apt-get install ocaml-nox opam python-bs4
  - opam init -y --compiler $SWITCH
  - eval `opam config env`
  - "[ -z $COVERAGE ] || opam install -y bisect_ppx ocveralls"
  - ocaml -version

script:
  - make install
  - make reverse-dependency-test
  - opam install -y ounit
  - make test
  - make performance-test
  - "[ -z $DOCS ] || make docs"
  - "[ -z $COVERAGE ] || ocveralls --prefix _build bisect*.out --send"
