env:
  - PPA=avsm/ocaml312+opam12 DOCS=no
  - PPA=avsm/ocaml40+opam12 DOCS=no
  - PPA=avsm/ocaml41+opam12
  - PPA=avsm/ocaml42+opam12

before_script:
  - sudo add-apt-repository -y ppa:$PPA
  - sudo apt-get update
  - sudo apt-get install ocaml-nox opam python-bs4
  - ocaml -version
  - opam init -y
  - eval `opam config env`

script:
  - make install
  - make reverse-dependency-test
  - opam install -y ounit
  - make test
  - make performance-test
  - "[ $DOCS == no ] || make docs"
